name: field_staff_tracker
description: "تطبيق متابعة فنيي الكهرباء وحضور المواقع بنظام الـ Geofencing"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
